sudo: required
services:
  - docker

before_install:
  - docker build -t goutam/docker-react -f Dockerfile.dev .

script:
  - docker run goutam/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-ap-south-1-538634141848"
  bucket_path: "react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

